from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, Float, ForeignKey
from sqlalchemy.orm import sessionmaker
import os
from dotenv import load_dotenv

# Carregar variáveis de ambiente do arquivo .env
load_dotenv()

user = os.getenv("POSTGRES_USER")
password = os.getenv("PASSWORD")
host = os.getenv("HOST")
port = os.getenv("PORT")
database = os.getenv("DATABASE")

# Criar a conexão com o banco de dados PostgreSQL
engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{database}')
metadata = MetaData()

cursos_table = Table('Cursos', metadata,
    Column('CursoID', Integer, primary_key=True, autoincrement=True, unique=True),
    Column('NomeCurso', String(100), nullable=False, unique=True)
)

disciplinas_table = Table('Disciplinas', metadata,
    Column('DisciplinaID', Integer, primary_key=True, autoincrement=True),
    Column('NomeDisciplina', String(100), nullable=False),
    Column('Periodo', Integer, nullable=False),
    Column('CursoID', Integer, ForeignKey('Cursos.CursoID'))
)

assuntos_semanais_table = Table('AssuntosSemanais', metadata,
    Column('AssuntoID', Integer, primary_key=True, autoincrement=True),
    Column('DisciplinaID', Integer, ForeignKey('Disciplinas.DisciplinaID')),
    Column('Semana', Integer, nullable=False),
    Column('Assunto', String(255), nullable=False)
)

historico_escolar_table = Table('HistoricoEscolar', metadata,
    Column('HistoricoID', Integer, primary_key=True, autoincrement=True),
    Column('DisciplinaID', Integer, ForeignKey('Disciplinas.DisciplinaID')),
    Column('Semestre', String(10), nullable=False),
    Column('AV1', Float),
    Column('AV2', Float),
    Column('Final', Float)
)

# Criar as tabelas no banco de dados
metadata.create_all(engine)

# Criar uma sessão
Session = sessionmaker(bind=engine)
session = Session()

# Inserir cursos
cursos = [
    {'NomeCurso': 'Ciência da Computação'},
    {'NomeCurso': 'Design'},
    {'NomeCurso': 'Gestão de TI'},
    {'NomeCurso': 'Análise e Desenvolvimento de Sistemas'},
    {'NomeCurso': 'Sistemas de Informação'}
]

for curso in cursos:
    session.execute(cursos_table.insert().values(curso))

session.commit()
disciplinas = {
    'Ciência da Computação': [
        ('Introdução à Computação', 1), ('Matemática para Computação', 1), ('Sistemas Digitais', 1),
        ('Fundamentos de Programação', 1), ('Fundamentos de Projeto 1', 1), ('Projeto 1', 1),
        ('Programação Imperativa e Funcional', 2), ('Algoritmos e Estrutura de Dados', 2),
        ('Lógica para Computação', 2), ('Fundamentos de Desenvolvimento de Software', 2),
        ('Fundamentos de Projetos 2', 2), ('Projeto 2', 2), ('Orientação a Objetos', 3),
        ('Infraestrutura de Hardware (AOC)', 3), ('Requisitos e Validação', 3),
        ('Infraestrutura de Software (SO)', 3), ('Fundamentos de Projetos 3', 3),
        ('Projeto 3', 3), ('Modelagem e Projeto de BD', 4), ('Infraestrutura de Comunicação (RSD)', 4),
        ('Estatística e Probabilidade', 4), ('Teoria da Computação', 4),
        ('Fundamentos de Projetos 4', 4), ('Projeto 4', 4), ('Teoria dos Grafos', 5),
        ('Análise e Visualização de Dados', 5), ('Interação Humano Computador', 5),
        ('Fundamentos de Computação Concorrente, Paralela e Distribuída', 5),
        ('Fundamentos de Projetos 5', 5), ('Projeto 5', 5), ('Aprendizado de Máquina', 6),
        ('Sistemas Embarcados', 6), ('Segurança da Informação', 6), ('Análise de Algoritmos', 6),
        ('Fundamentos de Projetos 6', 6), ('Projeto 6', 6), ('Eletiva 1', 7), ('Eletiva 2', 7),
        ('Tópicos Contemporâneos em Computação 1', 7), ('Tópicos Contemporâneos em Computação 2', 7),
        ('Fundamentos de Projetos 7', 7), ('Projeto 7', 7), ('Eletiva 3', 8),
        ('Eletiva 4', 8), ('Tópicos Contemporâneos em Computação 3', 8),
        ('Tópicos Contemporâneos em Computação 4', 8), ('Fundamentos de Projetos 8', 8),
        ('Projeto de Trabalho de Conclusão de Curso', 8)
    ],
    'Design': [
        ('Filosofia Prática', 1), ('Fundamentos da Pesquisa Social', 1), ('Sistemas Digitais', 1),
        ('Design da Experiência', 1), ('Fundamentos de Projeto 1', 1), ('Projeto 1', 1),
        ('Estudos de Futuro', 2), ('Análise e Comunicação da Pesquisa', 2),
        ('Semiótica', 2), ('Representação Visual', 2), ('Fundamentos de Projetos 2', 2),
        ('Projeto 2', 2), ('História e Teoria do Design I', 3), ('Projeto Gráfico', 3),
        ('Técnicas de Ideação', 3), ('Design Especulativo', 3), ('Fundamentos de Projetos 3', 3),
        ('Projeto 3', 3), ('Representação Tridimensional', 4), ('Design de Interfaces I', 4),
        ('Prototipação e Testes com Usuários I', 4), ('História e Teoria do Design II', 4),
        ('Fundamentos de Projetos 4', 4), ('Projeto 4', 4), ('Prototipação e Testes com Usuários II', 5),
        ('Design de Interfaces II', 5), ('Design de Produtos', 5), ('Design de Serviços', 5),
        ('Fundamentos de Projetos 5', 5), ('Projeto 5', 5), ('Fabricação Digital', 6),
        ('Design de Interfaces Ubíquas', 6), ('Teoria e Futuro do Design', 6),
        ('Design e Meio Ambiente', 6), ('Fundamentos de Projetos 6', 6), ('Projeto 6', 6),
        ('Eletiva 1', 7), ('Eletiva 2', 7), ('Tópicos Contemporâneos em Design 1', 7),
        ('Tópicos Contemporâneos em Design 2', 7), ('Fundamentos de Projetos 7', 7), ('Projeto 7', 7),
        ('Eletiva 3', 8), ('Eletiva 4', 8), ('Tópicos Contemporâneos em Design 3', 8),
        ('Tópicos Contemporâneos em Design 4', 8), ('Fundamentos de Projetos 8', 8),
        ('Projeto de Trabalho de Conclusão de Curso', 8)
    ],
    'Gestão de TI': [
        ('Introdução à Computação', 1), ('Matemática para Computação', 1), ('Design da Experiência', 1),
        ('Fundamentos de Programação', 1), ('Projeto 1', 1), ('Orientação a Objetos', 2),
        ('Técnicas de Ideação', 2), ('Gestão de Pessoas', 2), ('Fundamentos de Desenvolvimento de Software', 2),
        ('Projeto 2', 2), ('Estudos de Futuro', 3), ('Modelagem e Projeto de BD', 3),
        ('Requisitos e Validação', 3), ('Gestão de Projetos', 3), ('Projeto 3', 3),
        ('Negócios na Internet', 4), ('Interação Humano Máquina', 4), ('Estatística e Probabilidade', 4),
        ('Empreendedorismo', 4), ('Projeto 4', 4), ('Eletiva I', 5), ('Governança em TI', 5),
        ('Tópicos em Direito (LGPD)', 5), ('Análise e Visualização de Dados', 5), ('Projeto 5', 5)
    ],
    'Análise e Desenvolvimento de Sistemas': [
        ('Introdução à Computação', 1), ('Matemática para Computação', 1), ('Sistemas Digitais', 1),
        ('Fundamentos de Programação', 1), ('Projeto 1', 1), ('FP1: Gestão de Pessoas', 1),
        ('Programação Imperativa', 2), ('Interfaces Humano Computador', 2), ('Lógica para Computação', 2),
        ('Fundamentos de Desenvolvimento de Software', 2), ('Projeto 2', 2), ('FP2: Gestão de Projetos', 2),
        ('Orientação a Objetos', 3), ('Algoritmos e Estrutura de Dados', 3),
        ('Infraestrutura de Software (SO)', 3), ('Infraestrutura de Software (RSD)', 3),
        ('Estatística e Probabilidade', 3), ('Projeto 3', 3), ('Modelagem e Projeto de BD', 4),
        ('Requisitos, Projeto de Software e Validação', 4),
        ('Fundamentos de Computação Concorrente, Paralela e Distribuída', 4),
        ('Desenvolvimento Web', 4), ('Disciplina Optativa: Libras e Outras', 4), ('Projeto 4', 4),
        ('Segurança da Informação', 5), ('Desenvolvimento Mobile', 5), ('Eletiva 2', 5),
        ('Eletiva 3', 5), ('Negócios na Internet', 5), ('Projeto 5', 5)
    ],
    'Sistemas de Informação': [
        ('Introdução à Computação', 1), ('Matemática para Computação', 1), ('Sistemas Digitais', 1),
        ('Fundamentos de Programação', 1), ('Projeto 1', 1), ('FP1: Gestão de Pessoas', 1),
        ('Programação Imperativa', 2), ('Interfaces Humano Computador', 2), ('Lógica para Computação', 2),
        ('Fundamentos de Desenvolvimento de Software', 2), ('Projetos 2', 2), ('FP2: Gestão de Projetos', 2),
        ('Orientação a Objetos', 3), ('Infraestrutura de Hardware (AOC)', 3),
        ('Administração de Empresas', 3), ('Algoritmos e Estrutura de Dados', 3),
        ('Projeto 3', 3), ('FP3: Metodologia Científica', 3), ('Modelagem e Projeto de BD', 4),
        ('Infraestrutura de Comunicação (RSD)', 4), ('Estatística e Probabilidade', 4),
        ('Infraestrutura de Software (SO)', 4), ('Projeto 4', 4), ('FP4: Empreendedorismo', 4),
        ('Requisitos, Projeto de Software e Validação', 5), ('Análise e Visualização de Dados', 5),
        ('Pensamento Empresarial', 5), ('Fundamentos de Computação Concorrente, Paralela e Distribuída', 5),
        ('Projeto 5', 5), ('FP5: Marketing', 5), ('Aprendizado de Máquina', 6),
        ('Arquitetura de Software Nativa em Nuvem', 6), ('Segurança da Informação', 6),
        ('Desenvolvimento Web', 6), ('Projeto 6', 6), ('FP6: Tópicos em Direito', 6),
        ('Eletiva 1', 7), ('Eletiva 2', 7), ('DevOps', 7), ('Desenvolvimento Mobile', 7),
        ('Projeto 7', 7), ('Pré-Projeto de TCC', 7), ('Eletiva 3', 8), ('Eletiva 4', 8),
        ('Tópicos Contemporâneos em Sistema de Informação', 8), ('Governança de TI', 8),
        ('FP8: Acompanhamento de TCC', 8)
    ]
}

for curso, disps in disciplinas.items():
    curso_id = session.execute(cursos_table.select().where(cursos_table.c.NomeCurso == curso)).fetchone()[0]
    for disp in disps:
        print(f"Inserindo disciplina '{disp[0]}' do curso '{curso}' no período {disp[1]}")
        session.execute(disciplinas_table.insert().values(
            NomeDisciplina=disp[0],
            Periodo=disp[1],
            CursoID=curso_id
        ))

session.commit()

# Verificar se todas as disciplinas foram inseridas corretamente
for curso, disps in disciplinas.items():
    curso_id = session.execute(cursos_table.select().where(cursos_table.c.NomeCurso == curso)).fetchone()[0]
    for disp in disps:
        result = session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == disp[0]).where(disciplinas_table.c.CursoID == curso_id)).fetchone()
        if not result:
            print(f"Erro: Disciplina '{disp[0]}' não encontrada após inserção para o curso '{curso}'.")


# Notas para todos os períodos (1 a 7) do curso de Ciência da Computação
notas_historicos = [
    # 1º período
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Introdução à Computação')).fetchone()[0], 'Semestre': '2021.1', 'AV1': 8.0, 'AV2': 7.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Matemática para Computação')).fetchone()[0], 'Semestre': '2021.1', 'AV1': 7.0, 'AV2': 6.5, 'Final': 8.0},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Sistemas Digitais')).fetchone()[0], 'Semestre': '2021.1', 'AV1': 9.0, 'AV2': 8.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Fundamentos de Programação')).fetchone()[0], 'Semestre': '2021.1', 'AV1': 7.5, 'AV2': 7.0, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Fundamentos de Projeto 1')).fetchone()[0], 'Semestre': '2021.1', 'AV1': 8.0, 'AV2': 8.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Projeto 1')).fetchone()[0], 'Semestre': '2021.1', 'AV1': 9.5, 'AV2': 9.0, 'Final': None},

    # 2º período
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Programação Imperativa e Funcional')).fetchone()[0], 'Semestre': '2021.2', 'AV1': 8.5, 'AV2': 7.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Algoritmos e Estrutura de Dados')).fetchone()[0], 'Semestre': '2021.2', 'AV1': 7.0, 'AV2': 8.0, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Lógica para Computação')).fetchone()[0], 'Semestre': '2021.2', 'AV1': 6.5, 'AV2': 7.0, 'Final': 8.5},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Fundamentos de Desenvolvimento de Software')).fetchone()[0], 'Semestre': '2021.2', 'AV1': 8.0, 'AV2': 8.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Fundamentos de Projetos 2')).fetchone()[0], 'Semestre': '2021.2', 'AV1': 7.5, 'AV2': 7.0, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Projeto 2')).fetchone()[0], 'Semestre': '2021.2', 'AV1': 9.0, 'AV2': 8.5, 'Final': None},

    # 3º período
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Orientação a Objetos')).fetchone()[0], 'Semestre': '2022.1', 'AV1': 8.0, 'AV2': 8.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Infraestrutura de Hardware (AOC)')).fetchone()[0], 'Semestre': '2022.1', 'AV1': 7.0, 'AV2': 7.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Requisitos e Validação')).fetchone()[0], 'Semestre': '2022.1', 'AV1': 8.5, 'AV2': 8.0, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Infraestrutura de Software (SO)')).fetchone()[0], 'Semestre': '2022.1', 'AV1': 9.0, 'AV2': 8.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Fundamentos de Projetos 3')).fetchone()[0], 'Semestre': '2022.1', 'AV1': 7.5, 'AV2': 7.0, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Projeto 3')).fetchone()[0], 'Semestre': '2022.1', 'AV1': 9.5, 'AV2': 9.0, 'Final': None},

    # 4º período
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Modelagem e Projeto de BD')).fetchone()[0], 'Semestre': '2022.2', 'AV1': 8.0, 'AV2': 7.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Infraestrutura de Comunicação (RSD)')).fetchone()[0], 'Semestre': '2022.2', 'AV1': 7.0, 'AV2': 7.5, 'Final': 8.0},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Estatística e Probabilidade')).fetchone()[0], 'Semestre': '2022.2', 'AV1': 9.0, 'AV2': 8.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Teoria da Computação')).fetchone()[0], 'Semestre': '2022.2', 'AV1': 7.5, 'AV2': 7.0, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Fundamentos de Projetos 4')).fetchone()[0], 'Semestre': '2022.2', 'AV1': 8.0, 'AV2': 8.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Projeto 4')).fetchone()[0], 'Semestre': '2022.2', 'AV1': 9.5, 'AV2': 9.0, 'Final': None},

    # 5º período
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Teoria dos Grafos')).fetchone()[0], 'Semestre': '2023.1', 'AV1': 8.0, 'AV2': 8.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Análise e Visualização de Dados')).fetchone()[0], 'Semestre': '2023.1', 'AV1': 7.0, 'AV2': 7.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Interação Humano Computador')).fetchone()[0], 'Semestre': '2023.1', 'AV1': 8.5, 'AV2': 8.0, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Fundamentos de Computação Concorrente, Paralela e Distribuída')).fetchone()[0], 'Semestre': '2023.1', 'AV1': 9.0, 'AV2': 8.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Fundamentos de Projetos 5')).fetchone()[0], 'Semestre': '2023.1', 'AV1': 7.5, 'AV2': 7.0, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Projeto 5')).fetchone()[0], 'Semestre': '2023.1', 'AV1': 9.5, 'AV2': 9.0, 'Final': None},

    # 6º período
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Aprendizado de Máquina')).fetchone()[0], 'Semestre': '2023.2', 'AV1': 8.0, 'AV2': 7.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Sistemas Embarcados')).fetchone()[0], 'Semestre': '2023.2', 'AV1': 7.0, 'AV2': 7.5, 'Final': 8.0},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Segurança da Informação')).fetchone()[0], 'Semestre': '2023.2', 'AV1': 9.0, 'AV2': 8.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Análise de Algoritmos')).fetchone()[0], 'Semestre': '2023.2', 'AV1': 7.5, 'AV2': 7.0, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Fundamentos de Projetos 6')).fetchone()[0], 'Semestre': '2023.2', 'AV1': 8.0, 'AV2': 8.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Projeto 6')).fetchone()[0], 'Semestre': '2023.2', 'AV1': 9.5, 'AV2': 9.0, 'Final': None},

    # 7º período
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Eletiva 1')).fetchone()[0], 'Semestre': '2024.1', 'AV1': 7.0, 'AV2': 8.5, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Eletiva 2')).fetchone()[0], 'Semestre': '2024.1', 'AV1': 4.5, 'AV2': 5.5, 'Final': 10.0},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Tópicos Contemporâneos em Computação 1')).fetchone()[0], 'Semestre': '2024.1', 'AV1': 4.0, 'AV2': 10.0, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Tópicos Contemporâneos em Computação 2')).fetchone()[0], 'Semestre': '2024.1', 'AV1': 7.5, 'AV2': 7.0, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Fundamentos de Projetos 7')).fetchone()[0], 'Semestre': '2024.1', 'AV1': 7.8, 'AV2': 8.0, 'Final': None},
    {'DisciplinaID': session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == 'Projeto 7')).fetchone()[0], 'Semestre': '2024.1', 'AV1': 4.2, 'AV2': 7.5, 'Final': 8.0}
]

# Inserir notas no histórico escolar
for nota in notas_historicos:
    session.execute(historico_escolar_table.insert().values(nota))

session.commit()


# Verificar todas as disciplinas do curso de Design
curso_design_id = session.execute(cursos_table.select().where(cursos_table.c.NomeCurso == 'Design')).fetchone()[0]
design_disciplinas = session.execute(disciplinas_table.select().where(disciplinas_table.c.CursoID == curso_design_id)).fetchall()

for disciplina in design_disciplinas:
    print(disciplina)

session.commit()

assuntos_periodos = {
    1: {
        'Introdução à Computação': [
            {'Semana': 1, 'Assunto': 'História da Computação'},
            {'Semana': 2, 'Assunto': 'Conceitos Básicos de Computação'},
            {'Semana': 3, 'Assunto': 'Hardware e Software'},
            {'Semana': 4, 'Assunto': 'Sistemas Operacionais'},
            {'Semana': 5, 'Assunto': 'Redes de Computadores'},
            {'Semana': 6, 'Assunto': 'Segurança da Informação'},
            {'Semana': 7, 'Assunto': 'Algoritmos e Programação'},
            {'Semana': 8, 'Assunto': 'Estruturas de Dados'},
            {'Semana': 9, 'Assunto': 'Banco de Dados'},
            {'Semana': 10, 'Assunto': 'Inteligência Artificial'},
            {'Semana': 11, 'Assunto': 'Engenharia de Software'},
            {'Semana': 12, 'Assunto': 'Computação Gráfica'},
            {'Semana': 13, 'Assunto': 'Computação em Nuvem'},
            {'Semana': 14, 'Assunto': 'Computação Móvel'},
            {'Semana': 15, 'Assunto': 'Computação Ubíqua'},
            {'Semana': 16, 'Assunto': 'Desafios Atuais da Computação'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Matemática para Computação': [
            {'Semana': 1, 'Assunto': 'Fundamentos de Lógica'},
            {'Semana': 2, 'Assunto': 'Conjuntos'},
            {'Semana': 3, 'Assunto': 'Relações e Funções'},
            {'Semana': 4, 'Assunto': 'Princípios de Contagem'},
            {'Semana': 5, 'Assunto': 'Probabilidade'},
            {'Semana': 6, 'Assunto': 'Estatística Descritiva'},
            {'Semana': 7, 'Assunto': 'Distribuições de Probabilidade'},
            {'Semana': 8, 'Assunto': 'Estatística Inferencial'},
            {'Semana': 9, 'Assunto': 'Análise Combinatória'},
            {'Semana': 10, 'Assunto': 'Teoria dos Números'},
            {'Semana': 11, 'Assunto': 'Álgebra Linear'},
            {'Semana': 12, 'Assunto': 'Geometria Analítica'},
            {'Semana': 13, 'Assunto': 'Cálculo Diferencial'},
            {'Semana': 14, 'Assunto': 'Cálculo Integral'},
            {'Semana': 15, 'Assunto': 'Equações Diferenciais'},
            {'Semana': 16, 'Assunto': 'Transformadas de Laplace'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Sistemas Digitais': [
            {'Semana': 1, 'Assunto': 'Fundamentos de Sistemas Digitais'},
            {'Semana': 2, 'Assunto': 'Álgebra Booleana'},
            {'Semana': 3, 'Assunto': 'Portas Lógicas'},
            {'Semana': 4, 'Assunto': 'Circuitos Combinacionais'},
            {'Semana': 5, 'Assunto': 'Circuitos Sequenciais'},
            {'Semana': 6, 'Assunto': 'Flip-Flops e Latches'},
            {'Semana': 7, 'Assunto': 'Registradores e Contadores'},
            {'Semana': 8, 'Assunto': 'Memórias'},
            {'Semana': 9, 'Assunto': 'Conversores A/D e D/A'},
            {'Semana': 10, 'Assunto': 'Microprocessadores'},
            {'Semana': 11, 'Assunto': 'Arquitetura de Computadores'},
            {'Semana': 12, 'Assunto': 'Interfaceamento'},
            {'Semana': 13, 'Assunto': 'Sistemas Embarcados'},
            {'Semana': 14, 'Assunto': 'Sistemas de Tempo Real'},
            {'Semana': 15, 'Assunto': 'Redes de Computadores'},
            {'Semana': 16, 'Assunto': 'Segurança em Sistemas Digitais'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Fundamentos de Programação': [
            {'Semana': 1, 'Assunto': 'Introdução à Programação'},
            {'Semana': 2, 'Assunto': 'Variáveis e Tipos de Dados'},
            {'Semana': 3, 'Assunto': 'Estruturas de Controle'},
            {'Semana': 4, 'Assunto': 'Funções e Procedimentos'},
            {'Semana': 5, 'Assunto': 'Arrays e Matrizes'},
            {'Semana': 6, 'Assunto': 'Manipulação de Strings'},
            {'Semana': 7, 'Assunto': 'Estruturas de Dados'},
            {'Semana': 8, 'Assunto': 'Algoritmos de Busca e Ordenação'},
            {'Semana': 9, 'Assunto': 'Ponteiros e Alocação Dinâmica'},
            {'Semana': 10, 'Assunto': 'Recursão'},
            {'Semana': 11, 'Assunto': 'Introdução à Programação Orientada a Objetos'},
            {'Semana': 12, 'Assunto': 'Classes e Objetos'},
            {'Semana': 13, 'Assunto': 'Herança e Polimorfismo'},
            {'Semana': 14, 'Assunto': 'Tratamento de Exceções'},
            {'Semana': 15, 'Assunto': 'Manipulação de Arquivos'},
            {'Semana': 16, 'Assunto': 'Bibliotecas e Frameworks'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Fundamentos de Projeto 1': [
            {'Semana': 1, 'Assunto': 'Introdução ao Projeto de Software'},
            {'Semana': 2, 'Assunto': 'Metodologias de Desenvolvimento'},
            {'Semana': 3, 'Assunto': 'Planejamento de Projetos'},
            {'Semana': 4, 'Assunto': 'Levantamento de Requisitos'},
            {'Semana': 5, 'Assunto': 'Modelagem de Processos'},
            {'Semana': 6, 'Assunto': 'Diagramas de Caso de Uso'},
            {'Semana': 7, 'Assunto': 'Diagramas de Classes'},
            {'Semana': 8, 'Assunto': 'Diagramas de Sequência'},
            {'Semana': 9, 'Assunto': 'Diagramas de Atividades'},
            {'Semana': 10, 'Assunto': 'Diagramas de Estados'},
            {'Semana': 11, 'Assunto': 'Modelagem de Dados'},
            {'Semana': 12, 'Assunto': 'Normalização de Dados'},
            {'Semana': 13, 'Assunto': 'Desenvolvimento de Protótipos'},
            {'Semana': 14, 'Assunto': 'Teste de Software'},
            {'Semana': 15, 'Assunto': 'Gerenciamento de Configuração'},
            {'Semana': 16, 'Assunto': 'Documentação de Projetos'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Projeto 1': [
            {'Semana': 1, 'Assunto': 'Definição do Projeto'},
            {'Semana': 2, 'Assunto': 'Planejamento do Projeto'},
            {'Semana': 3, 'Assunto': 'Coleta de Requisitos'},
            {'Semana': 4, 'Assunto': 'Modelagem do Sistema'},
            {'Semana': 5, 'Assunto': 'Desenvolvimento do Protótipo'},
            {'Semana': 6, 'Assunto': 'Testes Iniciais'},
            {'Semana': 7, 'Assunto': 'Revisão do Protótipo'},
            {'Semana': 8, 'Assunto': 'Implementação de Funcionalidades'},
            {'Semana': 9, 'Assunto': 'Teste de Funcionalidades'},
            {'Semana': 10, 'Assunto': 'Integração de Componentes'},
            {'Semana': 11, 'Assunto': 'Otimização do Sistema'},
            {'Semana': 12, 'Assunto': 'Teste de Integração'},
            {'Semana': 13, 'Assunto': 'Correção de Erros'},
            {'Semana': 14, 'Assunto': 'Validação do Sistema'},
            {'Semana': 15, 'Assunto': 'Preparação para Entrega'},
            {'Semana': 16, 'Assunto': 'Documentação Final'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação do Projeto'}
        ]
    },
    2: {
        'Programação Imperativa e Funcional': [
            {'Semana': 1, 'Assunto': 'Introdução à Programação Imperativa'},
            {'Semana': 2, 'Assunto': 'Estruturas de Controle de Fluxo'},
            {'Semana': 3, 'Assunto': 'Funções e Procedimentos'},
            {'Semana': 4, 'Assunto': 'Tipos de Dados e Estruturas'},
            {'Semana': 5, 'Assunto': 'Recursão'},
            {'Semana': 6, 'Assunto': 'Introdução à Programação Funcional'},
            {'Semana': 7, 'Assunto': 'Funções de Alta Ordem'},
            {'Semana': 8, 'Assunto': 'Imutabilidade'},
            {'Semana': 9, 'Assunto': 'Expressões Lambda'},
            {'Semana': 10, 'Assunto': 'Recursão e Iteração'},
            {'Semana': 11, 'Assunto': 'Listas e Coleções'},
            {'Semana': 12, 'Assunto': 'Manipulação de Coleções'},
            {'Semana': 13, 'Assunto': 'Mapeamento e Filtragem'},
            {'Semana': 14, 'Assunto': 'Redução de Dados'},
            {'Semana': 15, 'Assunto': 'Tratamento de Exceções'},
            {'Semana': 16, 'Assunto': 'Programação Conjunta'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Algoritmos e Estrutura de Dados': [
            {'Semana': 1, 'Assunto': 'Introdução a Algoritmos'},
            {'Semana': 2, 'Assunto': 'Análise de Algoritmos'},
            {'Semana': 3, 'Assunto': 'Estruturas de Dados Lineares'},
            {'Semana': 4, 'Assunto': 'Listas Ligadas'},
            {'Semana': 5, 'Assunto': 'Pilhas e Filas'},
            {'Semana': 6, 'Assunto': 'Árvores'},
            {'Semana': 7, 'Assunto': 'Grafos'},
            {'Semana': 8, 'Assunto': 'Algoritmos de Busca'},
            {'Semana': 9, 'Assunto': 'Algoritmos de Ordenação'},
            {'Semana': 10, 'Assunto': 'Tabelas Hash'},
            {'Semana': 11, 'Assunto': 'Algoritmos Gulosos'},
            {'Semana': 12, 'Assunto': 'Programação Dinâmica'},
            {'Semana': 13, 'Assunto': 'Backtracking'},
            {'Semana': 14, 'Assunto': 'Divisão e Conquista'},
            {'Semana': 15, 'Assunto': 'Redes de Fluxo'},
            {'Semana': 16, 'Assunto': 'Algoritmos em Grafos'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Lógica para Computação': [
            {'Semana': 1, 'Assunto': 'Introdução à Lógica'},
            {'Semana': 2, 'Assunto': 'Proposições e Conectivos'},
            {'Semana': 3, 'Assunto': 'Tabelas Verdade'},
            {'Semana': 4, 'Assunto': 'Regras de Inferência'},
            {'Semana': 5, 'Assunto': 'Lógica de Predicados'},
            {'Semana': 6, 'Assunto': 'Quantificadores'},
            {'Semana': 7, 'Assunto': 'Resolução'},
            {'Semana': 8, 'Assunto': 'Teoremas de Lógica'},
            {'Semana': 9, 'Assunto': 'Indução Matemática'},
            {'Semana': 10, 'Assunto': 'Lógica Temporal'},
            {'Semana': 11, 'Assunto': 'Lógica Modal'},
            {'Semana': 12, 'Assunto': 'Lógica Fuzzy'},
            {'Semana': 13, 'Assunto': 'Autômatos e Linguagens Formais'},
            {'Semana': 14, 'Assunto': 'Teorema da Incompletude'},
            {'Semana': 15, 'Assunto': 'Semântica Formal'},
            {'Semana': 16, 'Assunto': 'Verificação de Programas'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Fundamentos de Desenvolvimento de Software': [
            {'Semana': 1, 'Assunto': 'Introdução ao Desenvolvimento de Software'},
            {'Semana': 2, 'Assunto': 'Metodologias Ágeis'},
            {'Semana': 3, 'Assunto': 'Scrum e Kanban'},
            {'Semana': 4, 'Assunto': 'Gestão de Projetos de Software'},
            {'Semana': 5, 'Assunto': 'Requisitos de Software'},
            {'Semana': 6, 'Assunto': 'Modelagem de Software'},
            {'Semana': 7, 'Assunto': 'Arquitetura de Software'},
            {'Semana': 8, 'Assunto': 'Padrões de Projeto'},
            {'Semana': 9, 'Assunto': 'Desenvolvimento de Software'},
            {'Semana': 10, 'Assunto': 'Testes de Software'},
            {'Semana': 11, 'Assunto': 'Manutenção de Software'},
            {'Semana': 12, 'Assunto': 'Qualidade de Software'},
            {'Semana': 13, 'Assunto': 'DevOps'},
            {'Semana': 14, 'Assunto': 'Integração Contínua'},
            {'Semana': 15, 'Assunto': 'Entrega Contínua'},
            {'Semana': 16, 'Assunto': 'Segurança de Software'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Fundamentos de Projetos 2': [
            {'Semana': 1, 'Assunto': 'Introdução ao Projeto de Software'},
            {'Semana': 2, 'Assunto': 'Metodologias de Desenvolvimento'},
            {'Semana': 3, 'Assunto': 'Planejamento de Projetos'},
            {'Semana': 4, 'Assunto': 'Levantamento de Requisitos'},
            {'Semana': 5, 'Assunto': 'Modelagem de Processos'},
            {'Semana': 6, 'Assunto': 'Diagramas de Caso de Uso'},
            {'Semana': 7, 'Assunto': 'Diagramas de Classes'},
            {'Semana': 8, 'Assunto': 'Diagramas de Sequência'},
            {'Semana': 9, 'Assunto': 'Diagramas de Atividades'},
            {'Semana': 10, 'Assunto': 'Diagramas de Estados'},
            {'Semana': 11, 'Assunto': 'Modelagem de Dados'},
            {'Semana': 12, 'Assunto': 'Normalização de Dados'},
            {'Semana': 13, 'Assunto': 'Desenvolvimento de Protótipos'},
            {'Semana': 14, 'Assunto': 'Teste de Software'},
            {'Semana': 15, 'Assunto': 'Gerenciamento de Configuração'},
            {'Semana': 16, 'Assunto': 'Documentação de Projetos'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Projeto 2': [
            {'Semana': 1, 'Assunto': 'Definição do Projeto'},
            {'Semana': 2, 'Assunto': 'Planejamento do Projeto'},
            {'Semana': 3, 'Assunto': 'Coleta de Requisitos'},
            {'Semana': 4, 'Assunto': 'Modelagem do Sistema'},
            {'Semana': 5, 'Assunto': 'Desenvolvimento do Protótipo'},
            {'Semana': 6, 'Assunto': 'Testes Iniciais'},
            {'Semana': 7, 'Assunto': 'Revisão do Protótipo'},
            {'Semana': 8, 'Assunto': 'Implementação de Funcionalidades'},
            {'Semana': 9, 'Assunto': 'Teste de Funcionalidades'},
            {'Semana': 10, 'Assunto': 'Integração de Componentes'},
            {'Semana': 11, 'Assunto': 'Otimização do Sistema'},
            {'Semana': 12, 'Assunto': 'Teste de Integração'},
            {'Semana': 13, 'Assunto': 'Correção de Erros'},
            {'Semana': 14, 'Assunto': 'Validação do Sistema'},
            {'Semana': 15, 'Assunto': 'Preparação para Entrega'},
            {'Semana': 16, 'Assunto': 'Documentação Final'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação do Projeto'}
        ]
    },
    3: {
        'Orientação a Objetos': [
            {'Semana': 1, 'Assunto': 'Introdução à Programação Orientada a Objetos'},
            {'Semana': 2, 'Assunto': 'Classes e Objetos'},
            {'Semana': 3, 'Assunto': 'Métodos e Mensagens'},
            {'Semana': 4, 'Assunto': 'Encapsulamento'},
            {'Semana': 5, 'Assunto': 'Herança'},
            {'Semana': 6, 'Assunto': 'Polimorfismo'},
            {'Semana': 7, 'Assunto': 'Composição'},
            {'Semana': 8, 'Assunto': 'Agregação'},
            {'Semana': 9, 'Assunto': 'Interfaces'},
            {'Semana': 10, 'Assunto': 'Classes Abstratas'},
            {'Semana': 11, 'Assunto': 'Tratamento de Exceções'},
            {'Semana': 12, 'Assunto': 'Coleções e Generics'},
            {'Semana': 13, 'Assunto': 'Entrada e Saída de Dados'},
            {'Semana': 14, 'Assunto': 'Serialização'},
            {'Semana': 15, 'Assunto': 'Reflexão'},
            {'Semana': 16, 'Assunto': 'Bibliotecas e APIs'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Infraestrutura de Hardware (AOC)': [
            {'Semana': 1, 'Assunto': 'Introdução à Infraestrutura de Hardware'},
            {'Semana': 2, 'Assunto': 'Componentes de um Computador'},
            {'Semana': 3, 'Assunto': 'Arquitetura de Processadores'},
            {'Semana': 4, 'Assunto': 'Memória'},
            {'Semana': 5, 'Assunto': 'Dispositivos de Armazenamento'},
            {'Semana': 6, 'Assunto': 'Barramentos'},
            {'Semana': 7, 'Assunto': 'Placas-Mãe'},
            {'Semana': 8, 'Assunto': 'Fontes de Alimentação'},
            {'Semana': 9, 'Assunto': 'Dispositivos de Entrada e Saída'},
            {'Semana': 10, 'Assunto': 'Monitores e Placas de Vídeo'},
            {'Semana': 11, 'Assunto': 'Redes de Computadores'},
            {'Semana': 12, 'Assunto': 'Segurança em Hardware'},
            {'Semana': 13, 'Assunto': 'Manutenção de Hardware'},
            {'Semana': 14, 'Assunto': 'Montagem de Computadores'},
            {'Semana': 15, 'Assunto': 'Diagnóstico e Solução de Problemas'},
            {'Semana': 16, 'Assunto': 'Tendências em Hardware'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Requisitos e Validação': [
            {'Semana': 1, 'Assunto': 'Introdução aos Requisitos de Software'},
            {'Semana': 2, 'Assunto': 'Tipos de Requisitos'},
            {'Semana': 3, 'Assunto': 'Levantamento de Requisitos'},
            {'Semana': 4, 'Assunto': 'Técnicas de Elicitação'},
            {'Semana': 5, 'Assunto': 'Modelagem de Requisitos'},
            {'Semana': 6, 'Assunto': 'Validação de Requisitos'},
            {'Semana': 7, 'Assunto': 'Verificação de Requisitos'},
            {'Semana': 8, 'Assunto': 'Gerenciamento de Requisitos'},
            {'Semana': 9, 'Assunto': 'Requisitos Não Funcionais'},
            {'Semana': 10, 'Assunto': 'Requisitos Funcionais'},
            {'Semana': 11, 'Assunto': 'Ferramentas de Gerenciamento de Requisitos'},
            {'Semana': 12, 'Assunto': 'Técnicas de Documentação de Requisitos'},
            {'Semana': 13, 'Assunto': 'Prototipação'},
            {'Semana': 14, 'Assunto': 'Casos de Uso'},
            {'Semana': 15, 'Assunto': 'Histórias de Usuário'},
            {'Semana': 16, 'Assunto': 'Diagramas de Requisitos'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Infraestrutura de Software (SO)': [
            {'Semana': 1, 'Assunto': 'Introdução aos Sistemas Operacionais'},
            {'Semana': 2, 'Assunto': 'Arquitetura de Sistemas Operacionais'},
            {'Semana': 3, 'Assunto': 'Gerenciamento de Processos'},
            {'Semana': 4, 'Assunto': 'Gerenciamento de Memória'},
            {'Semana': 5, 'Assunto': 'Sistemas de Arquivos'},
            {'Semana': 6, 'Assunto': 'Entrada e Saída'},
            {'Semana': 7, 'Assunto': 'Redes e Comunicação'},
            {'Semana': 8, 'Assunto': 'Segurança de Sistemas Operacionais'},
            {'Semana': 9, 'Assunto': 'Virtualização'},
            {'Semana': 10, 'Assunto': 'Sistemas Distribuídos'},
            {'Semana': 11, 'Assunto': 'Sistemas de Tempo Real'},
            {'Semana': 12, 'Assunto': 'Tolerância a Falhas'},
            {'Semana': 13, 'Assunto': 'Gerenciamento de Recursos'},
            {'Semana': 14, 'Assunto': 'Monitoração de Sistemas'},
            {'Semana': 15, 'Assunto': 'Desempenho de Sistemas'},
            {'Semana': 16, 'Assunto': 'Tendências em Sistemas Operacionais'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Fundamentos de Projetos 3': [
            {'Semana': 1, 'Assunto': 'Introdução ao Projeto de Software'},
            {'Semana': 2, 'Assunto': 'Metodologias de Desenvolvimento'},
            {'Semana': 3, 'Assunto': 'Planejamento de Projetos'},
            {'Semana': 4, 'Assunto': 'Levantamento de Requisitos'},
            {'Semana': 5, 'Assunto': 'Modelagem de Processos'},
            {'Semana': 6, 'Assunto': 'Diagramas de Caso de Uso'},
            {'Semana': 7, 'Assunto': 'Diagramas de Classes'},
            {'Semana': 8, 'Assunto': 'Diagramas de Sequência'},
            {'Semana': 9, 'Assunto': 'Diagramas de Atividades'},
            {'Semana': 10, 'Assunto': 'Diagramas de Estados'},
            {'Semana': 11, 'Assunto': 'Modelagem de Dados'},
            {'Semana': 12, 'Assunto': 'Normalização de Dados'},
            {'Semana': 13, 'Assunto': 'Desenvolvimento de Protótipos'},
            {'Semana': 14, 'Assunto': 'Teste de Software'},
            {'Semana': 15, 'Assunto': 'Gerenciamento de Configuração'},
            {'Semana': 16, 'Assunto': 'Documentação de Projetos'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Projeto 3': [
            {'Semana': 1, 'Assunto': 'Definição do Projeto'},
            {'Semana': 2, 'Assunto': 'Planejamento do Projeto'},
            {'Semana': 3, 'Assunto': 'Coleta de Requisitos'},
            {'Semana': 4, 'Assunto': 'Modelagem do Sistema'},
            {'Semana': 5, 'Assunto': 'Desenvolvimento do Protótipo'},
            {'Semana': 6, 'Assunto': 'Testes Iniciais'},
            {'Semana': 7, 'Assunto': 'Revisão do Protótipo'},
            {'Semana': 8, 'Assunto': 'Implementação de Funcionalidades'},
            {'Semana': 9, 'Assunto': 'Teste de Funcionalidades'},
            {'Semana': 10, 'Assunto': 'Integração de Componentes'},
            {'Semana': 11, 'Assunto': 'Otimização do Sistema'},
            {'Semana': 12, 'Assunto': 'Teste de Integração'},
            {'Semana': 13, 'Assunto': 'Correção de Erros'},
            {'Semana': 14, 'Assunto': 'Validação do Sistema'},
            {'Semana': 15, 'Assunto': 'Preparação para Entrega'},
            {'Semana': 16, 'Assunto': 'Documentação Final'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação do Projeto'}
        ]
    },
    4: {
        'Modelagem e Projeto de BD': [
            {'Semana': 1, 'Assunto': 'Introdução a Banco de Dados'},
            {'Semana': 2, 'Assunto': 'Modelagem Conceitual'},
            {'Semana': 3, 'Assunto': 'Modelo Entidade-Relacionamento'},
            {'Semana': 4, 'Assunto': 'Modelagem Lógica'},
            {'Semana': 5, 'Assunto': 'Modelagem Física'},
            {'Semana': 6, 'Assunto': 'Linguagem SQL'},
            {'Semana': 7, 'Assunto': 'Normalização de Dados'},
            {'Semana': 8, 'Assunto': 'Desempenho de Banco de Dados'},
            {'Semana': 9, 'Assunto': 'Transações'},
            {'Semana': 10, 'Assunto': 'Controle de Concorrência'},
            {'Semana': 11, 'Assunto': 'Recuperação de Banco de Dados'},
            {'Semana': 12, 'Assunto': 'Segurança de Banco de Dados'},
            {'Semana': 13, 'Assunto': 'Tópicos Avançados em SQL'},
            {'Semana': 14, 'Assunto': 'Procedures e Triggers'},
            {'Semana': 15, 'Assunto': 'Banco de Dados Distribuídos'},
            {'Semana': 16, 'Assunto': 'Data Warehousing'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Infraestrutura de Comunicação (RSD)': [
            {'Semana': 1, 'Assunto': 'Introdução a Redes de Computadores'},
            {'Semana': 2, 'Assunto': 'Camada Física'},
            {'Semana': 3, 'Assunto': 'Camada de Enlace'},
            {'Semana': 4, 'Assunto': 'Camada de Rede'},
            {'Semana': 5, 'Assunto': 'Camada de Transporte'},
            {'Semana': 6, 'Assunto': 'Camada de Aplicação'},
            {'Semana': 7, 'Assunto': 'Protocolos de Comunicação'},
            {'Semana': 8, 'Assunto': 'Endereçamento IP'},
            {'Semana': 9, 'Assunto': 'Redes Locais'},
            {'Semana': 10, 'Assunto': 'Redes Metropolitanas'},
            {'Semana': 11, 'Assunto': 'Redes de Longa Distância'},
            {'Semana': 12, 'Assunto': 'Segurança de Redes'},
            {'Semana': 13, 'Assunto': 'Redes Sem Fio'},
            {'Semana': 14, 'Assunto': 'Redes de Sensores'},
            {'Semana': 15, 'Assunto': 'Redes Definidas por Software'},
            {'Semana': 16, 'Assunto': 'Tendências em Redes'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Estatística e Probabilidade': [
            {'Semana': 1, 'Assunto': 'Introdução à Estatística'},
            {'Semana': 2, 'Assunto': 'Probabilidade'},
            {'Semana': 3, 'Assunto': 'Distribuições Discretas'},
            {'Semana': 4, 'Assunto': 'Distribuições Contínuas'},
            {'Semana': 5, 'Assunto': 'Estatística Descritiva'},
            {'Semana': 6, 'Assunto': 'Inferência Estatística'},
            {'Semana': 7, 'Assunto': 'Estimação de Parâmetros'},
            {'Semana': 8, 'Assunto': 'Testes de Hipóteses'},
            {'Semana': 9, 'Assunto': 'Regressão Linear'},
            {'Semana': 10, 'Assunto': 'Análise de Variância'},
            {'Semana': 11, 'Assunto': 'Séries Temporais'},
            {'Semana': 12, 'Assunto': 'Análise Multivariada'},
            {'Semana': 13, 'Assunto': 'Métodos Não Paramétricos'},
            {'Semana': 14, 'Assunto': 'Data Mining'},
            {'Semana': 15, 'Assunto': 'Aprendizado de Máquina'},
            {'Semana': 16, 'Assunto': 'Visualização de Dados'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Teoria da Computação': [
            {'Semana': 1, 'Assunto': 'Introdução à Teoria da Computação'},
            {'Semana': 2, 'Assunto': 'Máquinas de Turing'},
            {'Semana': 3, 'Assunto': 'Autômatos Finitos'},
            {'Semana': 4, 'Assunto': 'Linguagens Regulares'},
            {'Semana': 5, 'Assunto': 'Linguagens Livres de Contexto'},
            {'Semana': 6, 'Assunto': 'Gramáticas'},
            {'Semana': 7, 'Assunto': 'Autômatos com Pilha'},
            {'Semana': 8, 'Assunto': 'Autômatos Lineares Limitados'},
            {'Semana': 9, 'Assunto': 'Complexidade Computacional'},
            {'Semana': 10, 'Assunto': 'Redução de Problemas'},
            {'Semana': 11, 'Assunto': 'Problemas Decidíveis'},
            {'Semana': 12, 'Assunto': 'Problemas Indecidíveis'},
            {'Semana': 13, 'Assunto': 'Classes de Complexidade'},
            {'Semana': 14, 'Assunto': 'NP-Completude'},
            {'Semana': 15, 'Assunto': 'P vs NP'},
            {'Semana': 16, 'Assunto': 'Computabilidade e Complexidade'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Fundamentos de Projetos 4': [
            {'Semana': 1, 'Assunto': 'Introdução ao Projeto de Software'},
            {'Semana': 2, 'Assunto': 'Metodologias de Desenvolvimento'},
            {'Semana': 3, 'Assunto': 'Planejamento de Projetos'},
            {'Semana': 4, 'Assunto': 'Levantamento de Requisitos'},
            {'Semana': 5, 'Assunto': 'Modelagem de Processos'},
            {'Semana': 6, 'Assunto': 'Diagramas de Caso de Uso'},
            {'Semana': 7, 'Assunto': 'Diagramas de Classes'},
            {'Semana': 8, 'Assunto': 'Diagramas de Sequência'},
            {'Semana': 9, 'Assunto': 'Diagramas de Atividades'},
            {'Semana': 10, 'Assunto': 'Diagramas de Estados'},
            {'Semana': 11, 'Assunto': 'Modelagem de Dados'},
            {'Semana': 12, 'Assunto': 'Normalização de Dados'},
            {'Semana': 13, 'Assunto': 'Desenvolvimento de Protótipos'},
            {'Semana': 14, 'Assunto': 'Teste de Software'},
            {'Semana': 15, 'Assunto': 'Gerenciamento de Configuração'},
            {'Semana': 16, 'Assunto': 'Documentação de Projetos'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Projeto 4': [
            {'Semana': 1, 'Assunto': 'Definição do Projeto'},
            {'Semana': 2, 'Assunto': 'Planejamento do Projeto'},
            {'Semana': 3, 'Assunto': 'Coleta de Requisitos'},
            {'Semana': 4, 'Assunto': 'Modelagem do Sistema'},
            {'Semana': 5, 'Assunto': 'Desenvolvimento do Protótipo'},
            {'Semana': 6, 'Assunto': 'Testes Iniciais'},
            {'Semana': 7, 'Assunto': 'Revisão do Protótipo'},
            {'Semana': 8, 'Assunto': 'Implementação de Funcionalidades'},
            {'Semana': 9, 'Assunto': 'Teste de Funcionalidades'},
            {'Semana': 10, 'Assunto': 'Integração de Componentes'},
            {'Semana': 11, 'Assunto': 'Otimização do Sistema'},
            {'Semana': 12, 'Assunto': 'Teste de Integração'},
            {'Semana': 13, 'Assunto': 'Correção de Erros'},
            {'Semana': 14, 'Assunto': 'Validação do Sistema'},
            {'Semana': 15, 'Assunto': 'Preparação para Entrega'},
            {'Semana': 16, 'Assunto': 'Documentação Final'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação do Projeto'}
        ]
    },
    5: {
        'Teoria dos Grafos': [
            {'Semana': 1, 'Assunto': 'Introdução à Teoria dos Grafos'},
            {'Semana': 2, 'Assunto': 'Representação de Grafos'},
            {'Semana': 3, 'Assunto': 'Caminhos e Ciclos'},
            {'Semana': 4, 'Assunto': 'Conectividade'},
            {'Semana': 5, 'Assunto': 'Árvores e Florestas'},
            {'Semana': 6, 'Assunto': 'Algoritmos de Busca em Grafos'},
            {'Semana': 7, 'Assunto': 'Grafos Planários'},
            {'Semana': 8, 'Assunto': 'Coloração de Grafos'},
            {'Semana': 9, 'Assunto': 'Grafos Dirigidos'},
            {'Semana': 10, 'Assunto': 'Fluxo em Redes'},
            {'Semana': 11, 'Assunto': 'Grafos Eulerianos e Hamiltonianos'},
            {'Semana': 12, 'Assunto': 'Algoritmos de Grafos'},
            {'Semana': 13, 'Assunto': 'Aplicações de Grafos'},
            {'Semana': 14, 'Assunto': 'Teoremas em Teoria dos Grafos'},
            {'Semana': 15, 'Assunto': 'Grafos e Complexidade'},
            {'Semana': 16, 'Assunto': 'Projeto em Teoria dos Grafos'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Análise e Visualização de Dados': [
            {'Semana': 1, 'Assunto': 'Introdução à Análise de Dados'},
            {'Semana': 2, 'Assunto': 'Coleta de Dados'},
            {'Semana': 3, 'Assunto': 'Limpeza de Dados'},
            {'Semana': 4, 'Assunto': 'Exploração de Dados'},
            {'Semana': 5, 'Assunto': 'Visualização de Dados'},
            {'Semana': 6, 'Assunto': 'Ferramentas de Visualização'},
            {'Semana': 7, 'Assunto': 'Análise Exploratória de Dados'},
            {'Semana': 8, 'Assunto': 'Análise Estatística de Dados'},
            {'Semana': 9, 'Assunto': 'Modelos Preditivos'},
            {'Semana': 10, 'Assunto': 'Técnicas de Machine Learning'},
            {'Semana': 11, 'Assunto': 'Avaliação de Modelos'},
            {'Semana': 12, 'Assunto': 'Visualização Interativa'},
            {'Semana': 13, 'Assunto': 'Storytelling com Dados'},
            {'Semana': 14, 'Assunto': 'Casos de Estudo'},
            {'Semana': 15, 'Assunto': 'Tendências em Análise de Dados'},
            {'Semana': 16, 'Assunto': 'Projeto em Análise de Dados'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Interação Humano Computador': [
            {'Semana': 1, 'Assunto': 'Introdução à Interação Humano Computador'},
            {'Semana': 2, 'Assunto': 'Princípios de Design de Interfaces'},
            {'Semana': 3, 'Assunto': 'Usabilidade'},
            {'Semana': 4, 'Assunto': 'Design Centrado no Usuário'},
            {'Semana': 5, 'Assunto': 'Avaliação de Usabilidade'},
            {'Semana': 6, 'Assunto': 'Protótipos de Interfaces'},
            {'Semana': 7, 'Assunto': 'Ferramentas de Design de Interfaces'},
            {'Semana': 8, 'Assunto': 'Interface Homem-Máquina'},
            {'Semana': 9, 'Assunto': 'Interfaces Multimodais'},
            {'Semana': 10, 'Assunto': 'Acessibilidade'},
            {'Semana': 11, 'Assunto': 'Interação em Dispositivos Móveis'},
            {'Semana': 12, 'Assunto': 'Interfaces Naturais'},
            {'Semana': 13, 'Assunto': 'Interação em Realidade Virtual'},
            {'Semana': 14, 'Assunto': 'Técnicas de Avaliação'},
            {'Semana': 15, 'Assunto': 'Casos de Estudo'},
            {'Semana': 16, 'Assunto': 'Tendências em IHC'},
            {'Semana': 17, 'Assunto': 'Projeto em IHC'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Fundamentos de Computação Concorrente, Paralela e Distribuída': [
            {'Semana': 1, 'Assunto': 'Introdução à Computação Concorrente'},
            {'Semana': 2, 'Assunto': 'Modelos de Concorrência'},
            {'Semana': 3, 'Assunto': 'Programação Concorrente'},
            {'Semana': 4, 'Assunto': 'Introdução à Computação Paralela'},
            {'Semana': 5, 'Assunto': 'Arquiteturas Paralelas'},
            {'Semana': 6, 'Assunto': 'Programação Paralela'},
            {'Semana': 7, 'Assunto': 'Sistemas de Memória Compartilhada'},
            {'Semana': 8, 'Assunto': 'Introdução à Computação Distribuída'},
            {'Semana': 9, 'Assunto': 'Modelos de Computação Distribuída'},
            {'Semana': 10, 'Assunto': 'Comunicação em Sistemas Distribuídos'},
            {'Semana': 11, 'Assunto': 'Sincronização'},
            {'Semana': 12, 'Assunto': 'Algoritmos Distribuídos'},
            {'Semana': 13, 'Assunto': 'Tolerância a Falhas'},
            {'Semana': 14, 'Assunto': 'Sistemas Distribuídos'},
            {'Semana': 15, 'Assunto': 'Segurança em Sistemas Distribuídos'},
            {'Semana': 16, 'Assunto': 'Tendências em Computação Concorrente, Paralela e Distribuída'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Fundamentos de Projetos 5': [
            {'Semana': 1, 'Assunto': 'Introdução ao Projeto de Software'},
            {'Semana': 2, 'Assunto': 'Metodologias de Desenvolvimento'},
            {'Semana': 3, 'Assunto': 'Planejamento de Projetos'},
            {'Semana': 4, 'Assunto': 'Levantamento de Requisitos'},
            {'Semana': 5, 'Assunto': 'Modelagem de Processos'},
            {'Semana': 6, 'Assunto': 'Diagramas de Caso de Uso'},
            {'Semana': 7, 'Assunto': 'Diagramas de Classes'},
            {'Semana': 8, 'Assunto': 'Diagramas de Sequência'},
            {'Semana': 9, 'Assunto': 'Diagramas de Atividades'},
            {'Semana': 10, 'Assunto': 'Diagramas de Estados'},
            {'Semana': 11, 'Assunto': 'Modelagem de Dados'},
            {'Semana': 12, 'Assunto': 'Normalização de Dados'},
            {'Semana': 13, 'Assunto': 'Desenvolvimento de Protótipos'},
            {'Semana': 14, 'Assunto': 'Teste de Software'},
            {'Semana': 15, 'Assunto': 'Gerenciamento de Configuração'},
            {'Semana': 16, 'Assunto': 'Documentação de Projetos'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Projeto 5': [
            {'Semana': 1, 'Assunto': 'Definição do Projeto'},
            {'Semana': 2, 'Assunto': 'Planejamento do Projeto'},
            {'Semana': 3, 'Assunto': 'Coleta de Requisitos'},
            {'Semana': 4, 'Assunto': 'Modelagem do Sistema'},
            {'Semana': 5, 'Assunto': 'Desenvolvimento do Protótipo'},
            {'Semana': 6, 'Assunto': 'Testes Iniciais'},
            {'Semana': 7, 'Assunto': 'Revisão do Protótipo'},
            {'Semana': 8, 'Assunto': 'Implementação de Funcionalidades'},
            {'Semana': 9, 'Assunto': 'Teste de Funcionalidades'},
            {'Semana': 10, 'Assunto': 'Integração de Componentes'},
            {'Semana': 11, 'Assunto': 'Otimização do Sistema'},
            {'Semana': 12, 'Assunto': 'Teste de Integração'},
            {'Semana': 13, 'Assunto': 'Correção de Erros'},
            {'Semana': 14, 'Assunto': 'Validação do Sistema'},
            {'Semana': 15, 'Assunto': 'Preparação para Entrega'},
            {'Semana': 16, 'Assunto': 'Documentação Final'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação do Projeto'}
        ]
    },
    6: {
        'Aprendizado de Máquina': [
            {'Semana': 1, 'Assunto': 'Introdução ao Aprendizado de Máquina'},
            {'Semana': 2, 'Assunto': 'Pré-processamento de Dados'},
            {'Semana': 3, 'Assunto': 'Algoritmos de Aprendizado Supervisionado'},
            {'Semana': 4, 'Assunto': 'Algoritmos de Aprendizado Não Supervisionado'},
            {'Semana': 5, 'Assunto': 'Regressão Linear e Logística'},
            {'Semana': 6, 'Assunto': 'Árvores de Decisão'},
            {'Semana': 7, 'Assunto': 'Florestas Aleatórias'},
            {'Semana': 8, 'Assunto': 'Máquinas de Vetores de Suporte'},
            {'Semana': 9, 'Assunto': 'Redes Neurais'},
            {'Semana': 10, 'Assunto': 'Redes Neurais Convolucionais'},
            {'Semana': 11, 'Assunto': 'Redes Neurais Recorrentes'},
            {'Semana': 12, 'Assunto': 'Clusterização'},
            {'Semana': 13, 'Assunto': 'Redução de Dimensionalidade'},
            {'Semana': 14, 'Assunto': 'Análise de Componentes Principais'},
            {'Semana': 15, 'Assunto': 'Validação Cruzada'},
            {'Semana': 16, 'Assunto': 'Avaliação de Modelos'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Sistemas Embarcados': [
            {'Semana': 1, 'Assunto': 'Introdução a Sistemas Embarcados'},
            {'Semana': 2, 'Assunto': 'Arquiteturas de Sistemas Embarcados'},
            {'Semana': 3, 'Assunto': 'Processadores Embarcados'},
            {'Semana': 4, 'Assunto': 'Interfaces de Entrada e Saída'},
            {'Semana': 5, 'Assunto': 'Memórias em Sistemas Embarcados'},
            {'Semana': 6, 'Assunto': 'Sistemas Operacionais Embarcados'},
            {'Semana': 7, 'Assunto': 'Desenvolvimento de Software Embarcado'},
            {'Semana': 8, 'Assunto': 'Linguagens de Programação para Sistemas Embarcados'},
            {'Semana': 9, 'Assunto': 'Comunicação em Sistemas Embarcados'},
            {'Semana': 10, 'Assunto': 'Protocolos de Comunicação'},
            {'Semana': 11, 'Assunto': 'Redes de Sensores'},
            {'Semana': 12, 'Assunto': 'Segurança em Sistemas Embarcados'},
            {'Semana': 13, 'Assunto': 'Testes e Validação'},
            {'Semana': 14, 'Assunto': 'Projetos de Sistemas Embarcados'},
            {'Semana': 15, 'Assunto': 'Aplicações de Sistemas Embarcados'},
            {'Semana': 16, 'Assunto': 'Tendências em Sistemas Embarcados'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Segurança da Informação': [
            {'Semana': 1, 'Assunto': 'Introdução à Segurança da Informação'},
            {'Semana': 2, 'Assunto': 'Políticas de Segurança'},
            {'Semana': 3, 'Assunto': 'Criptografia'},
            {'Semana': 4, 'Assunto': 'Controles de Acesso'},
            {'Semana': 5, 'Assunto': 'Autenticação e Autorização'},
            {'Semana': 6, 'Assunto': 'Segurança em Redes'},
            {'Semana': 7, 'Assunto': 'Segurança em Aplicações Web'},
            {'Semana': 8, 'Assunto': 'Segurança em Banco de Dados'},
            {'Semana': 9, 'Assunto': 'Segurança em Sistemas Operacionais'},
            {'Semana': 10, 'Assunto': 'Gestão de Incidentes'},
            {'Semana': 11, 'Assunto': 'Análise Forense'},
            {'Semana': 12, 'Assunto': 'Normas e Regulamentações'},
            {'Semana': 13, 'Assunto': 'Auditoria de Sistemas'},
            {'Semana': 14, 'Assunto': 'Gestão de Riscos'},
            {'Semana': 15, 'Assunto': 'Plano de Continuidade de Negócios'},
            {'Semana': 16, 'Assunto': 'Segurança em Nuvem'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Análise de Algoritmos': [
            {'Semana': 1, 'Assunto': 'Introdução à Análise de Algoritmos'},
            {'Semana': 2, 'Assunto': 'Notação Assintótica'},
            {'Semana': 3, 'Assunto': 'Complexidade de Algoritmos'},
            {'Semana': 4, 'Assunto': 'Algoritmos de Busca'},
            {'Semana': 5, 'Assunto': 'Algoritmos de Ordenação'},
            {'Semana': 6, 'Assunto': 'Algoritmos de Grafos'},
            {'Semana': 7, 'Assunto': 'Programação Dinâmica'},
            {'Semana': 8, 'Assunto': 'Algoritmos Gulosos'},
            {'Semana': 9, 'Assunto': 'Divisão e Conquista'},
            {'Semana': 10, 'Assunto': 'Redes de Fluxo'},
            {'Semana': 11, 'Assunto': 'Algoritmos Probabilísticos'},
            {'Semana': 12, 'Assunto': 'Redução de Problemas'},
            {'Semana': 13, 'Assunto': 'P vs NP'},
            {'Semana': 14, 'Assunto': 'NP-Completude'},
            {'Semana': 15, 'Assunto': 'Teoria da Complexidade'},
            {'Semana': 16, 'Assunto': 'Técnicas Avançadas de Análise'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Fundamentos de Projetos 6': [
            {'Semana': 1, 'Assunto': 'Introdução ao Projeto de Software'},
            {'Semana': 2, 'Assunto': 'Metodologias de Desenvolvimento'},
            {'Semana': 3, 'Assunto': 'Planejamento de Projetos'},
            {'Semana': 4, 'Assunto': 'Levantamento de Requisitos'},
            {'Semana': 5, 'Assunto': 'Modelagem de Processos'},
            {'Semana': 6, 'Assunto': 'Diagramas de Caso de Uso'},
            {'Semana': 7, 'Assunto': 'Diagramas de Classes'},
            {'Semana': 8, 'Assunto': 'Diagramas de Sequência'},
            {'Semana': 9, 'Assunto': 'Diagramas de Atividades'},
            {'Semana': 10, 'Assunto': 'Diagramas de Estados'},
            {'Semana': 11, 'Assunto': 'Modelagem de Dados'},
            {'Semana': 12, 'Assunto': 'Normalização de Dados'},
            {'Semana': 13, 'Assunto': 'Desenvolvimento de Protótipos'},
            {'Semana': 14, 'Assunto': 'Teste de Software'},
            {'Semana': 15, 'Assunto': 'Gerenciamento de Configuração'},
            {'Semana': 16, 'Assunto': 'Documentação de Projetos'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Projeto 6': [
            {'Semana': 1, 'Assunto': 'Definição do Projeto'},
            {'Semana': 2, 'Assunto': 'Planejamento do Projeto'},
            {'Semana': 3, 'Assunto': 'Coleta de Requisitos'},
            {'Semana': 4, 'Assunto': 'Modelagem do Sistema'},
            {'Semana': 5, 'Assunto': 'Desenvolvimento do Protótipo'},
            {'Semana': 6, 'Assunto': 'Testes Iniciais'},
            {'Semana': 7, 'Assunto': 'Revisão do Protótipo'},
            {'Semana': 8, 'Assunto': 'Implementação de Funcionalidades'},
            {'Semana': 9, 'Assunto': 'Teste de Funcionalidades'},
            {'Semana': 10, 'Assunto': 'Integração de Componentes'},
            {'Semana': 11, 'Assunto': 'Otimização do Sistema'},
            {'Semana': 12, 'Assunto': 'Teste de Integração'},
            {'Semana': 13, 'Assunto': 'Correção de Erros'},
            {'Semana': 14, 'Assunto': 'Validação do Sistema'},
            {'Semana': 15, 'Assunto': 'Preparação para Entrega'},
            {'Semana': 16, 'Assunto': 'Documentação Final'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação do Projeto'}
        ],
    },
    7: {
        'Eletiva 1': [
            {'Semana': 1, 'Assunto': 'Introdução ao ESP32 e AWS IoT'},
            {'Semana': 2, 'Assunto': 'Configuração do ambiente de desenvolvimento'},
            {'Semana': 3, 'Assunto': 'Programação básica do ESP32'},
            {'Semana': 4, 'Assunto': 'Integração do ESP32 com sensores'},
            {'Semana': 5, 'Assunto': 'Conectividade WiFi e Bluetooth'},
            {'Semana': 6, 'Assunto': 'Introdução ao AWS IoT'},
            {'Semana': 7, 'Assunto': 'Configuração do AWS IoT Core'},
            {'Semana': 8, 'Assunto': 'Publicação e assinatura de mensagens MQTT'},
            {'Semana': 9, 'Assunto': 'Criação de regras e ações no AWS IoT'},
            {'Semana': 10, 'Assunto': 'Integração do ESP32 com AWS IoT'},
            {'Semana': 11, 'Assunto': 'Monitoramento e depuração'},
            {'Semana': 12, 'Assunto': 'Segurança em IoT'},
            {'Semana': 13, 'Assunto': 'Projeto prático: sistema de monitoramento'},
            {'Semana': 14, 'Assunto': 'Armazenamento de dados na nuvem'},
            {'Semana': 15, 'Assunto': 'Análise de dados IoT'},
            {'Semana': 16, 'Assunto': 'Automação com AWS Lambda'},
            {'Semana': 17, 'Assunto': 'Desenvolvimento de dashboards'},
            {'Semana': 18, 'Assunto': 'Manutenção e atualizações OTA'},
            {'Semana': 19, 'Assunto': 'Testes e validação do projeto'},
            {'Semana': 20, 'Assunto': 'Apresentação final do projeto'}
        ],
        'Eletiva 2': [
            {'Semana': 1, 'Assunto': 'Introdução à Engenharia de Software Avançada'},
            {'Semana': 2, 'Assunto': 'Modelagem de Software'},
            {'Semana': 3, 'Assunto': 'Processos de Desenvolvimento de Software'},
            {'Semana': 4, 'Assunto': 'Gestão de Requisitos'},
            {'Semana': 5, 'Assunto': 'Arquitetura de Software'},
            {'Semana': 6, 'Assunto': 'Padrões de Projeto'},
            {'Semana': 7, 'Assunto': 'Qualidade de Software'},
            {'Semana': 8, 'Assunto': 'Testes de Software'},
            {'Semana': 9, 'Assunto': 'Metodologias Ágeis'},
            {'Semana': 10, 'Assunto': 'Gerenciamento de Projetos de Software'},
            {'Semana': 11, 'Assunto': 'DevOps e Integração Contínua'},
            {'Semana': 12, 'Assunto': 'Manutenção e Evolução de Software'},
            {'Semana': 13, 'Assunto': 'Engenharia de Software para Sistemas Complexos'},
            {'Semana': 14, 'Assunto': 'Reutilização de Software'},
            {'Semana': 15, 'Assunto': 'Ferramentas de Suporte ao Desenvolvimento'},
            {'Semana': 16, 'Assunto': 'Segurança em Engenharia de Software'},
            {'Semana': 17, 'Assunto': 'Projeto de Software'},
            {'Semana': 18, 'Assunto': 'Gestão de Configuração'},
            {'Semana': 19, 'Assunto': 'Métricas de Software'},
            {'Semana': 20, 'Assunto': 'Tendências em Engenharia de Software'}
        ],
        'Tópicos Contemporâneos em Computação 1': [
            {'Semana': 1, 'Assunto': 'Introdução à Visão Computacional'},
            {'Semana': 2, 'Assunto': 'Conceitos Básicos de Imagens Digitais'},
            {'Semana': 3, 'Assunto': 'Processamento de Imagens'},
            {'Semana': 4, 'Assunto': 'Detecção de Bordas'},
            {'Semana': 5, 'Assunto': 'Segmentação de Imagens'},
            {'Semana': 6, 'Assunto': 'Representação e Descrição de Imagens'},
            {'Semana': 7, 'Assunto': 'Reconhecimento de Padrões'},
            {'Semana': 8, 'Assunto': 'Classificação de Imagens'},
            {'Semana': 9, 'Assunto': 'Aprendizado de Máquina para Visão Computacional'},
            {'Semana': 10, 'Assunto': 'Redes Neurais Convolucionais'},
            {'Semana': 11, 'Assunto': 'Detecção de Objetos'},
            {'Semana': 12, 'Assunto': 'Rastreamento de Objetos'},
            {'Semana': 13, 'Assunto': 'Visão Estéreo'},
            {'Semana': 14, 'Assunto': 'Reconstrução 3D'},
            {'Semana': 15, 'Assunto': 'Aplicações de Visão Computacional'},
            {'Semana': 16, 'Assunto': 'Processamento de Vídeo'},
            {'Semana': 17, 'Assunto': 'Visão Computacional em Tempo Real'},
            {'Semana': 18, 'Assunto': 'Desafios Atuais em Visão Computacional'},
            {'Semana': 19, 'Assunto': 'Projeto Prático em Visão Computacional'},
            {'Semana': 20, 'Assunto': 'Apresentação Final do Projeto'}
        ],
        'Tópicos Contemporâneos em Computação 2': [
            {'Semana': 1, 'Assunto': 'Introdução à Computação em Nuvem'},
            {'Semana': 2, 'Assunto': 'Modelos de Serviço em Nuvem'},
            {'Semana': 3, 'Assunto': 'Modelos de Implantação em Nuvem'},
            {'Semana': 4, 'Assunto': 'Arquitetura de Nuvem'},
            {'Semana': 5, 'Assunto': 'Tecnologias de Virtualização'},
            {'Semana': 6, 'Assunto': 'Gerenciamento de Recursos em Nuvem'},
            {'Semana': 7, 'Assunto': 'Armazenamento em Nuvem'},
            {'Semana': 8, 'Assunto': 'Redes em Nuvem'},
            {'Semana': 9, 'Assunto': 'Segurança em Nuvem'},
            {'Semana': 10, 'Assunto': 'Serviços de Nuvem Pública e Privada'},
            {'Semana': 11, 'Assunto': 'Computação sem Servidor (Serverless)'},
            {'Semana': 12, 'Assunto': 'Escalabilidade e Desempenho'},
            {'Semana': 13, 'Assunto': 'Gerenciamento de Custos em Nuvem'},
            {'Semana': 14, 'Assunto': 'DevOps e Nuvem'},
            {'Semana': 15, 'Assunto': 'Desenvolvimento de Aplicações Nativas da Nuvem'},
            {'Semana': 16, 'Assunto': 'Monitoramento e Logging'},
            {'Semana': 17, 'Assunto': 'Recuperação de Desastres e Continuidade de Negócios'},
            {'Semana': 18, 'Assunto': 'Tendências e Inovações em Nuvem'},
            {'Semana': 19, 'Assunto': 'Projeto Prático em Computação em Nuvem'},
            {'Semana': 20, 'Assunto': 'Apresentação Final do Projeto'}
        ],
        'Fundamentos de Projetos 7': [
            {'Semana': 1, 'Assunto': 'Introdução ao TCC'},
            {'Semana': 2, 'Assunto': 'Escolha do Tema do TCC'},
            {'Semana': 3, 'Assunto': 'Revisão de Literatura'},
            {'Semana': 4, 'Assunto': 'Desenvolvimento da Proposta'},
            {'Semana': 5, 'Assunto': 'Metodologia de Pesquisa'},
            {'Semana': 6, 'Assunto': 'Planejamento do Projeto'},
            {'Semana': 7, 'Assunto': 'Coleta de Dados'},
            {'Semana': 8, 'Assunto': 'Análise de Dados'},
            {'Semana': 9, 'Assunto': 'Desenvolvimento do Referencial Teórico'},
            {'Semana': 10, 'Assunto': 'Redação do TCC'},
            {'Semana': 11, 'Assunto': 'Elaboração dos Resultados'},
            {'Semana': 12, 'Assunto': 'Discussão dos Resultados'},
            {'Semana': 13, 'Assunto': 'Conclusões e Recomendações'},
            {'Semana': 14, 'Assunto': 'Revisão e Edição'},
            {'Semana': 15, 'Assunto': 'Normas e Formatação'},
            {'Semana': 16, 'Assunto': 'Preparação para a Defesa'},
            {'Semana': 17, 'Assunto': 'Simulação da Defesa'},
            {'Semana': 18, 'Assunto': 'Ajustes Finais'},
            {'Semana': 19, 'Assunto': 'Entrega do TCC'},
            {'Semana': 20, 'Assunto': 'Apresentação Final'}
        ],
        'Projeto 7': [
            {'Semana': 1, 'Assunto': 'Definição do escopo do projeto'},
            {'Semana': 2, 'Assunto': 'Pesquisa e levantamento de requisitos'},
            {'Semana': 3, 'Assunto': 'Desenvolvimento inicial'},
            {'Semana': 4, 'Assunto': 'Prototipagem e testes iniciais'},
            {'Semana': 5, 'Assunto': 'Aprimoramento do projeto'},
            {'Semana': 6, 'Assunto': 'Implementação de funcionalidades'},
            {'Semana': 7, 'Assunto': 'Testes e validação'},
            {'Semana': 8, 'Assunto': 'Revisão e ajustes'},
            {'Semana': 9, 'Assunto': 'Desenvolvimento contínuo'},
            {'Semana': 10, 'Assunto': 'Integração de componentes'},
            {'Semana': 11, 'Assunto': 'Teste de integração'},
            {'Semana': 12, 'Assunto': 'Otimização de desempenho'},
            {'Semana': 13, 'Assunto': 'Documentação do projeto'},
            {'Semana': 14, 'Assunto': 'Preparação para apresentação'},
            {'Semana': 15, 'Assunto': 'Revisão final'},
            {'Semana': 16, 'Assunto': 'Testes finais'},
            {'Semana': 17, 'Assunto': 'Correção de bugs'},
            {'Semana': 18, 'Assunto': 'Preparação do relatório final'},
            {'Semana': 19, 'Assunto': 'Feedback e melhorias'},
            {'Semana': 20, 'Assunto': 'Apresentação final e entrega'}
        ]
    },
    8: {
        'Eletiva 1': [
            {'Semana': 1, 'Assunto': 'Introdução ao Desenvolvimento Frontend'},
            {'Semana': 2, 'Assunto': 'HTML5 e Estrutura de Páginas Web'},
            {'Semana': 3, 'Assunto': 'CSS3 e Design Responsivo'},
            {'Semana': 4, 'Assunto': 'JavaScript e Interatividade'},
            {'Semana': 5, 'Assunto': 'Bibliotecas e Frameworks (React, Angular)'},
            {'Semana': 6, 'Assunto': 'Gerenciamento de Estado'},
            {'Semana': 7, 'Assunto': 'APIs e Comunicação com Backend'},
            {'Semana': 8, 'Assunto': 'Ferramentas de Desenvolvimento (Webpack, Babel)'},
            {'Semana': 9, 'Assunto': 'Testes de Software para Frontend'},
            {'Semana': 10, 'Assunto': 'Acessibilidade Web'},
            {'Semana': 11, 'Assunto': 'Otimização de Performance'},
            {'Semana': 12, 'Assunto': 'Segurança em Aplicações Web'},
            {'Semana': 13, 'Assunto': 'Projetos Práticos com HTML, CSS e JavaScript'},
            {'Semana': 14, 'Assunto': 'Introdução ao Desenvolvimento Mobile'},
            {'Semana': 15, 'Assunto': 'Aplicações Web Progressivas (PWAs)'},
            {'Semana': 16, 'Assunto': 'Automação de Tarefas com Gulp e Grunt'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 18, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 19, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Projetos'}
        ],
        'Eletiva 2': [
            {'Semana': 1, 'Assunto': 'Introdução à Criação de Portfólio'},
            {'Semana': 2, 'Assunto': 'Identidade Visual e Branding'},
            {'Semana': 3, 'Assunto': 'Ferramentas de Design (Photoshop, Illustrator)'},
            {'Semana': 4, 'Assunto': 'Layout e Composição'},
            {'Semana': 5, 'Assunto': 'Tipografia'},
            {'Semana': 6, 'Assunto': 'Cores e Psicologia das Cores'},
            {'Semana': 7, 'Assunto': 'Design de Interfaces'},
            {'Semana': 8, 'Assunto': 'Experiência do Usuário (UX)'},
            {'Semana': 9, 'Assunto': 'Design de Interação'},
            {'Semana': 10, 'Assunto': 'Protótipos e Wireframes'},
            {'Semana': 11, 'Assunto': 'Ferramentas de Prototipação (Figma, Sketch)'},
            {'Semana': 12, 'Assunto': 'Animação para Web'},
            {'Semana': 13, 'Assunto': 'Desenvolvimento de Portfólio Online'},
            {'Semana': 14, 'Assunto': 'SEO para Portfólio'},
            {'Semana': 15, 'Assunto': 'Marketing Digital para Portfólio'},
            {'Semana': 16, 'Assunto': 'Projeto Prático 1'},
            {'Semana': 17, 'Assunto': 'Projeto Prático 2'},
            {'Semana': 18, 'Assunto': 'Revisão e Prova Final'},
            {'Semana': 19, 'Assunto': 'Feedback e Melhorias'},
            {'Semana': 20, 'Assunto': 'Apresentação dos Portfólios'}
        ]
    }
}

for periodo, disciplinas in assuntos_periodos.items():
    for disciplina, assuntos in disciplinas.items():
        result = session.execute(disciplinas_table.select().where(disciplinas_table.c.NomeDisciplina == disciplina)).fetchone()
        if result is None:
            print(f"Erro: Disciplina '{disciplina}' não encontrada.")
            continue
        disciplina_id = result[0]
        for assunto in assuntos:
            session.execute(assuntos_semanais_table.insert().values(
                DisciplinaID=disciplina_id,
                Semana=assunto['Semana'],
                Assunto=assunto['Assunto']
            ))

session.commit()
