from dotenv import load_dotenv
import os

load_dotenv()


key = os.getenv("SECRET_KEY")

SECRET_KEY = key
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60
RESET_TOKEN_EXPIRY_MINUTES = 30

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")
GOOGLE_PROJECT_ID = os.getenv("GOOGLE_PROJECT_ID")
CLASSROOM_API_VERSION = os.getenv("CLASSROOM_API_VERSION")
LOGFIRE_API_KEY = os.getenv("LOGFIRE_API_KEY")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")

SMTP_SERVER = os.getenv("SMTP_SERVER")
STMP_PORT = int(os.getenv("SMTP_PORT"))
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD")